# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 16:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 12, 10, 16, 45, 26, 806970)),
            preserve_default=False,
        ),
    ]
